apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wordpress-storage
  hostPath:
    path: "/mnt/wordpress-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - controlplane